version: '3.9'
services:
  mysql:
    image: mysql:8.1
    container_name: dev-mysql
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: soomteo
      MYSQL_DATABASE: soomteo
      MYSQL_USER: soomteo
      MYSQL_PASSWORD: soomteo
    ports:
      - "3307:3306"
    volumes:
      - mysql-data:/var/lib/mysql
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost"]
      interval: 5s
      timeout: 5s
      retries: 10
      
  spring:
      build:
        context: ./backend/spring/backend
        dockerfile: Dockerfile.dev
      container_name: dev-spring
      ports:
        - "8080:8080"
      volumes:
        - ./backend/spring/backend:/app
      environment:
        SPRING_DATASOURCE_URL: jdbc:mysql://mysql:3306/soomteo
        SPRING_DATASOURCE_USERNAME: soomteo
        SPRING_DATASOURCE_PASSWORD: soomteo
        GRADLE_USER_HOME: /app/.gradle
        JAVA_TOOL_OPTIONS: "-XX:+UseContainerSupport -XX:MaxRAMPercentage=75.0"
      depends_on:
        mysql:
          condition: service_healthy
        
  node:
    build:
      context: ./backend/node
      dockerfile: Dockerfile.dev
    container_name: dev-node
    ports:
      - "8081:8081"
    volumes:
      - ./backend/node:/app
      - node_modules:/app/node_modules
    depends_on:
      - mysql
      - spring
      
  redis:
    image: redis:7
    container_name: redis-soomteo
    restart: always
    ports:
      - "6379:6379"
    command: ["redis-server", "--appendonly", "yes"]
    volumes:
      - redis-data:/data

volumes:
  mysql-data:
  node_modules:
  redis-data: